---
- name: Add ruby ppa
  apt_repository: repo='ppa:brightbox/ruby-ng'
- name: Add nginx ppa
  apt_repository: repo='ppa:nginx/stable'

- name: apt-get update
  apt: update_cache=yes

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - unattended-upgrades
    - build-essential
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - curl
    - openssh-server
    - checkinstall
    - openssl
    - libssl1.0.0
    - logrotate
    - pkg-config
    - cmake
    - git-core
    - postfix
    - tree
    - ack-grep
    - xtail
    - htop
    - emacs24-nox
    - ruby2.1
    - ruby2.1-dev
    - imagemagick
    - nodejs-legacy
    - npm
    - mysql-client
    - libmysqlclient-dev
    - sqlite3
    - libsqlite3-dev
    - libcurl4-openssl-dev
    - nginx
    - libxslt-dev
    - libxml2-dev

- name: Create app user
  user:
   name: app
   state: present
   createhome: yes
   shell: /bin/bash

# Configure git
- command: "git config --global user.name 'app'"
  sudo_user: app
- command: "git config --global user.email 'app@sewuniquebybonnie.com'"
  sudo_user: app
- command: "git config --global core.autocrlf input"
  sudo_user: app

# Configure updates
- command: "dpkg-reconfigure -f noninteractive unattended-upgrades"
  sudo: yes

# Configure ssh
- file: path="/home/{{item}}/.ssh" state="directory" owner={{item}} group={{item}}
  with_items: user_names
- copy: src="authorized_keys" dest="/home/{{item}}/.ssh/authorized_keys" owner={{item}} group={{item}} mode=0600
  with_items: user_names
- copy: src="id_rsa" dest="/home/{{item}}/.ssh/id_rsa" owner={{item}} group={{item}} mode=0600
  with_items: user_names
- copy: src="id_rsa.pub" dest="/home/{{item}}/.ssh/id_rsa.pub" owner={{item}} group={{item}} mode=0600
  with_items: user_names

# Configure bash
- copy: src="bashrc" dest="/home/{{item}}/.bashrc" owner={{item}} group={{item}} mode=0755
  with_items: user_names

# Copy nginx file
- template: src="nginx.conf" dest="/etc/nginx/sites-available/sew-unique"

# Make sure directories exist
- file: path=/var/sew-unique state=directory owner=app group=app
- file: path=/var/sew-unique/shared state=directory owner=app group=app
- file: path=/var/sew-unique/shared/log state=directory owner=app group=app
- file: path=/var/sew-unique/shared/pids state=directory owner=app group=app
- file: path=/var/sew-unique/shared/sockets state=directory owner=app group=app
- file: path=/var/sew-unique/shared/bundle state=directory owner=app group=app
- file: path=/var/sew-unique/releases state=directory owner=app group=app

# Install gems
- name: Install bundler
  gem: name=bundler state=present user_install=false
- name: Install rake
  gem: name=rake state=present user_install=false
- name: Install sass
  gem: name=sass state=present user_install=false

- file: path="/etc/nginx/sites-enabled/sew-unique" state=link src="/etc/nginx/sites-available/sew-unique" owner=root group=root
- file: path="/etc/nginx/sites-enabled/default" state=absent

# Restart nginx
- service: name="nginx" state="restarted" enabled="yes"
