---
- name: Create the sewunique-{{environment_name}}-web security group
  local_action:
    module: ec2_group
    region: us-west-2
    vpc_id: "{{vpc_id}}"
    name: "sewunique-{{environment_name}}-web"
    description: "Sew Unique {{environment_name}} web security group"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0

- name: Create the instance
  local_action:
    module: ec2
    key_name: ansible-sewunique-key
    group: "sewunique-{{environment_name}}-web"
    instance_type: "{{web_size}}"
    image: "{{web_ami}}"
    wait: yes
    region: us-west-2
    vpc_subnet_id: "{{subnet_id1}}"
    zone: us-west-2a
    volumes:
      - device_name: "/dev/sda1"
        volume_size: "{{web_volume_size}}"
        delete_on_termination: true
  register: ec2

- name: Add instances to host group
  local_action: add_host hostname={{item.public_ip}} groupname=new-instance
  with_items: ec2.instances

- name: Tag instances
  local_action: ec2_tag resource={{item.id}} region=us-west-2 state=present
  with_items: ec2.instances
  args:
    tags:
      Environment: "{{environment_name}}"
      Role: web
      Name: sewunique-{{environment_name}}-web
      App: sewunique

- name: Wait for instances to listen on port:22
  wait_for:
    state=started
    host={{ item.public_dns_name }}
    port=22
  with_items: ec2.instances
