defaults: &defaults
  access_key_id:
  secret_access_key:
  images_bucket: 'images.dev.sewuniquebybonnie.com'

development:
  <<: *defaults

test:
  <<: *defaults
  images_bucket: 'images.test.sewuniquebybonnie.com'

production:
  <<: *defaults
  images_bucket: 'images.sewuniquebybonnie.com'
