defaults: &defaults
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  images_bucket: 'images.dev.sewuniquebybonnie.com'

development:
  <<: *defaults

test:
  <<: *defaults
  images_bucket: 'images.test.sewuniquebybonnie.com'

production:
  <<: *defaults
  images_bucket: 'images.sewuniquebybonnie.com'
